[window]
width = 960
height = 600
fullscreen = false

[grid]
width = 960
height = 600

[mouse]
scroll_steps = 21

[tool]
min_effect_radius = 0.1
max_effect_radius = inf
height_brush_sensitivity = 0.02

[scene]
show_vertices = false
preserve_aspect_ratio = false